# Generated by Django 4.2.1 on 2023-06-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField(auto_now_add=True, verbose_name='appointment Date')),
                ('appointmentTime', models.TimeField(auto_now_add=True, verbose_name='appointment Time')),
                ('appointmentStatus', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Canceled', 'Canceled')], default='Scheduled', max_length=100)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=300)),
                ('doctorAddress', models.CharField(max_length=500)),
                ('doctorPhone', models.CharField(max_length=50)),
                ('specialisation', models.CharField(max_length=300)),
                ('certification', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=300)),
                ('patientAddress', models.CharField(max_length=500)),
                ('patientPhone', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('medical_history', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('medicationName', models.CharField(max_length=300)),
                ('dosage', models.CharField(max_length=300)),
                ('frequency', models.CharField(max_length=300)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ibn_sina.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ibn_sina.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ibn_sina.patient'),
        ),
    ]
